# azure-pipelines.yml

# Triggers: CI on main and workflow branches, and manual run support
trigger:
  - main

pool:
  name: "Default" # Use the default pool (Self-hosted agents)

variables:
  # Replace with your Docker Hub username
  dockerHubUser: "marwanabdelmoneim"
  imageName: "flask-demo"
  tag: "$(Build.BuildId)"

stages:
  - stage: Test
    displayName: "Run Unit Tests"
    jobs:
      - job: TestJob
        displayName: "Test Flask App"

        steps:
          - script: |
              # Create and activate a virtual environment
              python3 -m venv .venv
              source .venv/bin/activate

              # Now install dependencies into the active venv
              python3 -m pip install --upgrade pip
              pip3 install -r requirements.txt
            displayName: "Install dependencies in Venv"

          - script: |
              # Activate the venv again for this new task
              source .venv/bin/activate

              pip3 install pytest
              pytest tests/
            displayName: "Run tests in Venv"

  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    dependsOn: Test # This stage runs only if the 'Test' stage succeeds
    condition: succeeded()
    jobs:
      - job: BuildJob
        displayName: "Build and Push"
        steps:
          - task: Docker@2
            displayName: "Build and push image to Docker Hub"
            inputs:
              containerRegistry: "DockerHubConnection" # Must match your service connection name
              repository: "$(dockerHubUser)/$(imageName)"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(tag)
                latest
