# azure-pipelines.yml

# Triggers: CI on main and workflow branches, and manual run support
trigger:
  - main

pool:
  name: "Default" # Use the default pool (Self-hosted agents)

variables:
  # Replace with your Docker Hub username
  dockerHubUser: "marwanabdelmoneim"
  imageName: "flask-demo"
  tag: "$(Build.BuildId)"

stages:
  - stage: Test
    displayName: "Run Unit Tests"
    jobs:
      - job: TestJob
        displayName: "Test Flask App"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.12"
            displayName: "Use Python 3.12"

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: "Install dependencies"

          - script: |
              pip install pytest
              pytest tests/
            displayName: "Run tests with pytest"

  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    dependsOn: Test # This stage runs only if the 'Test' stage succeeds
    condition: succeeded()
    jobs:
      - job: BuildJob
        displayName: "Build and Push"
        steps:
          - task: Docker@2
            displayName: "Build and push image to Docker Hub"
            inputs:
              containerRegistry: "DockerHubConnection" # Must match your service connection name
              repository: "$(dockerHubUser)/$(imageName)"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(tag)
                latest
